### ISSUE TITLE
ESlint rule no-undef means calls to mx are seen as errors

### ISSUE THREAD

**Issue by LSFinaps** [Finaps/boilerplate-mendix-react-widget#1]
mx.data.action is used to call microflows from a widget. However, because of the no-undef rule in eslint, running npm run build will show an error.

It would be great if mx was either added as an external to the webpack config, or the rule was ignored for mx.

**Comment by erickles** [comment]
I've been working on this project as well (made a copy for my self), and a just removed the es-lint from webpack, working fine so far. Regarding Microflows, i've made this function:

```
executeMicroflow(mf, guid, cb) {

        const {lang} = this.props;

        if (mf && guid)
            window.mx.ui.action(mf, {
                params: {
                    applyto: "selection",
                    guids: [guid]
                },
                callback: lang.hitch(this, function (objs) {
                    if (cb && typeof cb === "function")
                        cb(objs);
                }),
                error: function (error) {
                    console.debug(error.description);
                }
            }, this);
    }
```
Any idea in how do i get the "guid" parameter?

**Comment by LSFinaps** [comment]
@erickles The guid is from a mendix object (MxObject in the Client Api), for example a context object passed by a dataview, which can be retrieved in the update method of the widget. Or they can be instantiated directly using the mendix client api. You can then call contextObject.getGuid() to get the guid of the the MxObject.

See the [Mendix Client Api](https://apidocs.mendix.com/7/client/mendix_lib_MxObject.html) for more details
